apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: etcd-operator-subscription
  namespace: seba
spec:
  channel: seba/local-charts-repo
  name: etcd-operator
  placement:
    placementRef:
      name: seba-placementrule
      kind: PlacementRule
      group: app.ibm.com
  packageOverrides:
  - packageName: etcd-operator
    packageOverrides:
    - path: spec.values
      value: |
        namespace: seba