apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: kafka-subscription
  namespace: seba
spec:
  channel: seba/google-incubator-repo
  name: kafka
  placement:
    placementRef:
      name: seba-placementrule
      kind: PlacementRule
      group: app.ibm.com
  packageOverrides:
  - packageName: kafka
    packageOverrides:
    - path: spec.values
      value: |
        namespace: seba