apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: voltha-subscription
  namespace: seba
  labels:
    purpose: seba-poc
spec:
  channel: seba-deployables/seba-helm-repo
  name: voltha
  packageFilter:
    version: 1.0.6
  placement:
    placementRef:
      name: seba-placementrule
      kind: PlacementRule
      group: app.ibm.com
  packageOverrides:
  - packageName: voltha
    packageOverrides:
    - path: spec.values
      value: |
        global:
          namespace: voltha
  overrides:
  - clusterName: "/"
    clusterOverrides:
    - path: "metadata.namespace"
      value: default