apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: voltha-subscription
  namespace: seba
spec:
  channel: seba/seba-helm-repo
  name: voltha
  packageFilter:
    version: 1.0.6
  placement:
    placementRef:
      name: seba-placementrule
      kind: PlacementRule
      group: app.ibm.com
  packageOverrides:
  - packageName: voltha
    packageOverrides:
    - path: spec.values
      value: |
        namespace: seba