apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: etcd-operator-subscription
  namespace: seba
  labels:
    purpose: seba-poc
spec:
  channel: seba-deployables/local-charts-repo
  name: etcd-operator
  packageFilter:
    version: 0.8.3
  placement:
    placementRef:
      name: seba-placementrule
      kind: PlacementRule
      group: app.ibm.com
  overrides:
    - clusterName: "/"
      clusterOverrides:
      - path: "metadata.namespace"
        value: default