apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: seba-subscription
  namespace: seba
  labels:
    purpose: seba-poc
spec:
  channel: seba-deployables/seba-helm-repo
  name: onos
  packageFilter:
    version: 1.1.3
  placement:
    placementRef:
      name: seba-placementrule
      kind: PlacementRule
      group: app.ibm.com
  overrides:
    - clusterName: "/"
      clusterOverrides:
      - path: "metadata.namespace"
        value: default
  packageOverrides:
  - packageName: onos
    packageOverrides:
    - path: spec.values
      value: |
        fullnameOverride: "onos"