apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: kafka-subscription
  namespace: seba
  labels:
    purpose: seba-poc
spec:
  channel: seba-deployables/google-incubator-repo
  name: kafka
  packageFilter:
    version: 0.13.3
  placement:
    placementRef:
      name: seba-placementrule
      kind: PlacementRule
      group: app.ibm.com
  packageOverrides:
  - packageName: kafka
    packageOverrides:
    - path: spec.values
      value: |
        persistence:
          enabled: false
          #enabled: false
          #size: 5Gi
        configurationOverrides:
          "offsets.topic.replication.factor": 3
          "log.retention.hours": 4
          "log.message.timestamp.type": "LogAppendTime"
        replicas: 3
        zookeeper:
          persistence:
            enabled: false
          replicaCount: 3
        fullnameOverride: "kafka"
  overrides:
    - clusterName: "/"
      clusterOverrides:
      - path: "metadata.namespace"
        value: default