apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: seba-application
  namespace: seba
# Application is namespace-scoped resource, it is not set here to let user apply to `current` namespace
spec:
  selector:
    matchLabels:
      purpose: seba-poc
  componentKinds:
  - group: app.ibm.com
    kind: Subscription
