apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: subscribed-seba-application
# Application is namespace-scoped resource, it is not set here to let user apply to `current` namespace
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - subscribed-seba-application
  componentKinds:
  - group: app.ibm.com
    kind: Subscription
